### ISSUE TITLE
我启动的时候报unsupport SQL_SERVER错，帮忙看看

### ISSUE THREAD

**Issue by yinguanhua** [alswl/yugong#10]
启动的时候就报这个错

我的配置文件
`yugong.database.source.username=sa
yugong.database.source.password=Aa123456
yugong.database.source.type=SQL_SERVER
yugong.database.source.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=test
yugong.database.source.encode=UTF-8
yugong.database.source.poolSize=30
yugong.database.target.url=jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true
yugong.database.target.username=root 
yugong.database.target.password=root
yugong.database.target.type=MYSQL
yugong.database.target.encode=UTF-8
yugong.database.target.poolSize=30
yugong.table.batchApply=true`
yugong.table.mode=ALL

报的错
`com.taobao.yugong.exception.YuGongException: unsupport SQL_SERVER
        at com.taobao.yugong.controller.YuGongController.chooseExtractor(YuGongController.java:407)
        at com.taobao.yugong.controller.YuGongController.chooseExtractor(YuGongController.java:411)
        at com.taobao.yugong.controller.YuGongController.start(YuGongController.java:206)
        at com.taobao.yugong.YugongApp.run(YugongApp.java:67)
        at com.taobao.yugong.YugongApp.main(YugongApp.java:55)`

**Comment by yinguanhua** [comment]
yugong.table.mode=ALL改为
yugong.table.mode=FULL就正常了
