### ISSUE TITLE
小数据量没有问题，大数据量，直接报错

### ISSUE THREAD

**Issue by yinguanhua** [alswl/yugong#12]
2021-07-21 16:07:11.462 [YuGongInstance-AukeysOrder.OrderInfo] ERROR com.taobao.yugong.controller.YuGongInstance - retry 1 ,something error happened. caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 30, maxActive 30
        at com.taobao.yugong.common.utils.thread.ExecutorTemplate.waitForResult(ExecutorTemplate.java:79)
        at com.taobao.yugong.applier.MultiThreadCheckRecordApplier.apply(MultiThreadCheckRecordApplier.java:97)
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
        at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 30, maxActive 30
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.taobao.yugong.common.utils.thread.ExecutorTemplate.waitForResult(ExecutorTemplate.java:77)
        ... 4 more
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 30, maxActive 30
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:331)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.queryColumns(TableMetaGenerator.java:294)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:86)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
        at com.taobao.yugong.applier.CheckRecordApplier.getSqlUnit(CheckRecordApplier.java:350)
        at com.taobao.yugong.applier.CheckRecordApplier.queryByBatch(CheckRecordApplier.java:111)
        at com.taobao.yugong.applier.CheckRecordApplier.doApply(CheckRecordApplier.java:93)
        at com.taobao.yugong.applier.MultiThreadCheckRecordApplier$1.run(MultiThreadCheckRecordApplier.java:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 30, maxActive 30
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1155)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:977)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:957)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:947)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:113)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
        ... 16 more

**Comment by alswl** [comment]
连接池申请连接超时，要么是数据库太慢了，要么是单行数据太大（导致 Request Latency 太高）。

解决：1、增大连接池数量，30 -> 60 试试，2、升级服务器配置。

**Comment by yinguanhua** [comment]
经观查测试，在大数据量迁移运行时，服务器CPU，内存，磁盘读写，无明显波动，经过一小段时间等待依然报错，目前已转向阿里云DataX3.0研究

**Comment by alswl** [comment]
@yinguanhua emm，你应该看 Druid 的连接池使用情况，可以用 Druid 提供的 Web UI。

不过 DataX 如果能满足你的需求也挺好的。
