### ISSUE TITLE
sqlserver到mysql，表配置能读取到，目标表库配置读取不到

### ISSUE THREAD

**Issue by jsnjcrane** [alswl/yugong#8]
2020-03-17 09:27:53.663 [YuGongInstance-AdventureWorks.test123] ERROR com.taobao.yugong.common.alarm.LogAlarmService - Alarm:com.taobao.yugong.exception.YuGongException: table[null.test123] is not found
	at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:83)
	at com.taobao.yugong.common.db.meta.TableMetaGenerator$$Lambda$4/293508253.doInConnection(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
	at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
	at com.taobao.yugong.applier.FullRecordApplier.getSqlUnit(FullRecordApplier.java:391)
	at com.taobao.yugong.applier.FullRecordApplier.doApply(FullRecordApplier.java:82)
	at com.taobao.yugong.applier.MultiThreadFullRecordApplier.apply(MultiThreadFullRecordApplier.java:108)
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
	at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
	at java.lang.Thread.run(Unknown Source)
 , Receiver:

**Comment by jsnjcrane** [comment]
yugong.database.source.url=jdbc:sqlserver://192.168.2.219:1433;databaseName=AdventureWorks
yugong.database.source.username=sa
yugong.database.source.password=123.asddsa
yugong.database.source.type=SQL_SERVER
yugong.database.source.encode=UTF-8
yugong.database.source.poolSize=200

yugong.database.target.url=jdbc:mysql://10.81.2.135:3306/test?autoReconnect=true
yugong.database.target.username=root
yugong.database.target.password=123456
yugong.database.target.type=MYSQL
yugong.database.target.encode=UTF-8
yugong.database.target.poolSize=200

**Comment by alswl** [comment]
看上去配置没啥问题。

**Comment by jsnjcrane** [comment]
yugong.database.source.url=jdbc:sqlserver://192.168.2.219:1433;databaseName=AdventureWorks
yugong.database.source.username=sa
yugong.database.source.password=123.asddsa
yugong.database.source.type=SQL_SERVER
yugong.database.source.encode=UTF-8
yugong.database.source.poolSize=200

yugong.database.target.url=jdbc:mysql://10.81.2.135:3306/test?autoReconnect=true
yugong.database.target.username=root
yugong.database.target.password=123456
yugong.database.target.type=MYSQL
yugong.database.target.encode=UTF-8
yugong.database.target.poolSize=200


#yugong.table.batchApply=true  # TODO
yugong.table.batchApply=true
yugong.table.onceCrawNum=1000
yugong.table.tpsLimit=0
# 忽略源表pk检查的表，多表用英文逗号分隔
yugong.table.ignorePkInspection=ShopOrderDetail,ShopOrderDetailMulti
# 分别列出需要指定的主键或联合主键
yugong.table.ignorePkInspection.ShopOrderDetail=OrderId,ProductId
yugong.table.ignorePkInspection.ShopOrderDetailMulti=OrderId,ProductId,MultiProductId

# use connection default schema
yugong.table.ignoreSchema=false
# skip Applier Load Db failed data
yugong.table.skipApplierException=false
#需要迁移的数据库表
yugong.table.white=test
yugong.table.black=
# tables use multi-thread enable or disable
# TODO test concurrent
yugong.table.concurrent.enable=true
# tables use multi-thread size
yugong.table.concurrent.size=6
# retry times 
yugong.table.retry.times=3
# retry interval or sleep time (ms)
yugong.table.retry.interval=1000
# MARK/FULL/INC/ALL(REC+FULL+INC)/CHECK/CLEAR
yugong.table.mode=FULL


# yugong extractor
yugong.extractor.dump=false
yugong.extractor.concurrent.enable=true
yugong.extractor.concurrent.global=false
yugong.extractor.concurrent.size=60
yugong.extractor.noupdate.sleep=1000
yugong.extractor.noupdate.thresold=0
yugong.extractor.once=false

# yugong applier
yugong.applier.concurrent.enable=true
yugong.applier.concurrent.global=false
yugong.applier.concurrent.size=20
yugong.applier.dump=false
# stats
yugong.stat.print.interval=5
yugong.progress.print.interval=1
# alarm email
yugong.alarm.email.host=
yugong.alarm.email.username=
yugong.alarm.email.password=
yugong.alarm.email.stmp.port=
yugong.alarm.email.ssl.support=
yugong.alarm.receiver=

**Comment by jsnjcrane** [comment]
[root@localhost yugong-feature-sql-server-to-mysql-overview]# java -jar yugong-shaded.jar -c sync-mssql-mysql.properties -y mssql-mysql.yaml
2020-03-17 10:20:29.482 [main] INFO  com.taobao.yugong.YugongApp - ## start the YuGong.
2020-03-17 10:20:29.619 [main] INFO  com.taobao.yugong.controller.YuGongController - check source database connection ...
2020-03-17 10:20:29.644 [main] INFO  com.taobao.yugong.controller.YuGongController - check source database is ok
2020-03-17 10:20:29.645 [main] INFO  com.taobao.yugong.controller.YuGongController - check target database connection ...
2020-03-17 10:20:29.674 [main] INFO  com.taobao.yugong.controller.YuGongController - check target database is ok
2020-03-17 10:20:29.674 [main] INFO  com.taobao.yugong.controller.YuGongController - check source tables read privileges ...
2020-03-17 10:20:29.761 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
2020-03-17 10:20:30.161 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-2} inited
2020-03-17 10:20:32.111 [main] INFO  com.taobao.yugong.controller.YuGongController - check source tables is ok.
2020-03-17 10:20:32.238 [main] INFO  com.taobao.yugong.controller.YuGongController - ## prepare start tables[1] with concurrent[6]
2020-03-17 10:20:32.307 [main] INFO  com.taobao.yugong.extractor.FullContinueExtractor - AdventureWorks.test start postion:0
2020-03-17 10:20:32.328 [main] INFO  com.taobao.yugong.controller.YuGongInstance - table[AdventureWorks.test] start successful. extractor:com.taobao.yugong.extractor.sqlserver.SqlServerFullRecordExtractor , applier:com.taobao.yugong.applier.MultiThreadFullRecordApplier, translator:[NameStyleDataTranslator(schemaTo=test, tableTo=null, columnCaseFormatFrom=UPPER_CAMEL, columnCaseFormatTo=LOWER_UNDERSCORE, tableCaseFormatFrom=UPPER_CAMEL, tableCaseFormatTo=LOWER_UNDERSCORE)]
2020-03-17 10:20:32.328 [main] INFO  com.taobao.yugong.YugongApp - ## the YuGong is running now ......
2020-03-17 10:20:32.330 [YuGongInstance-AdventureWorks.test] INFO  com.taobao.yugong.controller.YuGongInstance - table[AdventureWorks.test] is start
2020-03-17 10:20:32.331 [main] INFO  com.taobao.yugong.YugongApp - 
[YuGong Version Info]
[version ]Unknown
[hexVeision]Unknown
[date    ]Unknown
[branch  ]Unknown
[url     ]Unknown

2020-03-17 10:20:32.700 [YuGongInstance-AdventureWorks.test] ERROR com.taobao.yugong.controller.YuGongInstance - retry 1 ,something error happened. caused by com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:83)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
        at com.taobao.yugong.applier.FullRecordApplier.getSqlUnit(FullRecordApplier.java:391)
        at com.taobao.yugong.applier.FullRecordApplier.doApply(FullRecordApplier.java:82)
        at com.taobao.yugong.applier.MultiThreadFullRecordApplier.apply(MultiThreadFullRecordApplier.java:108)
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
        at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
        at java.lang.Thread.run(Thread.java:745)

2020-03-17 10:20:32.701 [YuGongInstance-AdventureWorks.test] ERROR com.taobao.yugong.common.alarm.LogAlarmService - Alarm:com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:83)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
        at com.taobao.yugong.applier.FullRecordApplier.getSqlUnit(FullRecordApplier.java:391)
        at com.taobao.yugong.applier.FullRecordApplier.doApply(FullRecordApplier.java:82)
        at com.taobao.yugong.applier.MultiThreadFullRecordApplier.apply(MultiThreadFullRecordApplier.java:108)
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
        at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
        at java.lang.Thread.run(Thread.java:745)
 , Receiver:
2020-03-17 10:20:33.703 [YuGongInstance-AdventureWorks.test] ERROR com.taobao.yugong.controller.YuGongInstance - retry 1 ,something error happened. caused by com.taobao.yugong.exception.YuGongException: com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:325)
        at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:83)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
        at com.taobao.yugong.applier.FullRecordApplier.getSqlUnit(FullRecordApplier.java:391)
        at com.taobao.yugong.applier.FullRecordApplier.doApply(FullRecordApplier.java:82)
        at com.taobao.yugong.applier.MultiThreadFullRecordApplier.apply(MultiThreadFullRecordApplier.java:108)
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
        ... 2 more

2020-03-17 10:20:33.703 [YuGongInstance-AdventureWorks.test] ERROR com.taobao.yugong.common.alarm.LogAlarmService - Alarm:com.taobao.yugong.exception.YuGongException: com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:325)
        at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:201)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.taobao.yugong.exception.YuGongException: table[null.test] is not found
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.lambda$getTableMeta$0(TableMetaGenerator.java:83)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
        at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:50)
        at com.taobao.yugong.applier.FullRecordApplier.getSqlUnit(FullRecordApplier.java:391)
        at com.taobao.yugong.applier.FullRecordApplier.doApply(FullRecordApplier.java:82)
        at com.taobao.yugong.applier.MultiThreadFullRecordApplier.apply(MultiThreadFullRecordApplier.java:108)
        at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:271)
        ... 2 more
 , Receiver:
2020-03-17 10:20:34.704 [YuGongInstance-AdventureWorks.test] INFO  com.taobao.yugong.controller.YuGongInstance - table[AdventureWorks.test] is error , current status:TABLE_END !
2020-03-17 10:20:34.705 [pool-3-thread-1] INFO  com.taobao.yugong.controller.YuGongInstance - table[AdventureWorks.test] stop successful. 
2020-03-17 10:20:37.705 [main] INFO  com.taobao.yugong.YugongApp - ## stop the YuGong
2020-03-17 10:20:37.710 [main] INFO  com.taobao.yugong.common.stats.ProgressTracer - {未启动:0,全量中:0,已完成:0,异常数:1}
2020-03-17 10:20:37.711 [main] INFO  com.taobao.yugong.common.stats.ProgressTracer - 异常数:[AdventureWorks.test]
2020-03-17 10:20:37.711 [main] INFO  com.taobao.yugong.common.stats.ProgressTracer - 已完成:[]
2020-03-17 10:20:37.716 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closed
2020-03-17 10:20:37.716 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-2} closed
2020-03-17 10:20:37.717 [main] INFO  com.taobao.yugong.YugongApp - ## YuGong is down.

**Comment by jsnjcrane** [comment]
@alswl 大神帮忙看下

**Comment by alswl** [comment]
使用我这个版本还需要配置 `yugong.yaml`，请问这里面配置了么，参考 https://github.com/alswl/yugong/blob/feature/sql-server-to-mysql-overview/yugong.yaml.sample

**Comment by jsnjcrane** [comment]
databases: 
  source:
    schema: AdventureWorks 
  target:
    schema: test 

table: 
  a: todo 
  b: todo 

extractor:
  a: todo 
  b: todo 

appiler:
  a: todo 
  b: todo 

translators:
  table:
    '*':
      - class: com.taobao.yugong.translator.NameTableMetaTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
    AnotherDemo:
      - class: com.taobao.yugong.translator.NameTableMetaTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
    ProductProperty: []
  record:
    '*':
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          schema_to: test
    'FrontCategory':
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_alias:
            BussinessID:
              - BusinessID
            IsHighLight:
              - IsHighlight
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: test
    A:
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_alias:
            Editdate:
              - EditDate
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: test
    B:
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_alias:
            Indate:
              - InDate
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: test
    C:
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          column_alias:
            Indate:
              - InDate
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: test
    D:
      - class: com.taobao.yugong.translator.ColumnFixDataTranslator
        properties:
          exclude_columns:
            - a
            - b
      - class: com.taobao.yugong.translator.NameStyleDataTranslator
        properties:
          column_case_format_from: UPPER_CAMEL
          column_case_format_to: LOWER_UNDERSCORE
          table_case_format_from: UPPER_CAMEL
          table_case_format_to: LOWER_UNDERSCORE
          schema_to: test

源库：AdventureWorks  目标库是mysql，库名是：test，大神是哪里配的有问题吗

**Comment by jsnjcrane** [comment]
@alswl 大神，有相关讨论群吗？方便交流些

**Comment by jsnjcrane** [comment]
可以跑通了感谢支持，还有个问题，这个sqlserver到mysql版本的怎样才能和oracle到mysql的一样可以一直运行。不用一直起任务？   @alswl

**Comment by alswl** [comment]
目前不支持，设计为单次任务运行。
